name: Manual Terraform Destroy

on:
  workflow_dispatch:

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    name: terraform-destroy

    steps:
      - name: Checkout and clone repo
        uses: actions/checkout@v4
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Setup Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCES_KEY }}
      - name: Terraform init
        working-directory: terraform
        run: terraform init
      - name: Destroy Terraform
        working-directory: terraform
        run: terraform destroy -auto-approve
