name: Manual Terraform Destroy

on:
  workflow_dispatch:

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    name: terraform-destroy
    env:
      TF_VAR_db_db: ${{ secrets.DB_DB }}
      TF_VAR_db_host: ${{ secrets.DB_HOST }}
      TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
      TF_VAR_db_port: ${{ secrets.DB_PORT }}
      TF_VAR_db_user: ${{ secrets.DB_USER }}

      TF_VAR_db_db_dw: ${{ secrets.DB_DW }}
      TF_VAR_db_host_dw: ${{ secrets.DB_HOST_DW }}
      TF_VAR_db_password_dw: ${{ secrets.DB_PASSWORD_DW }}
      TF_VAR_db_port_dw: ${{ secrets.DB_PORT_DW }}
      TF_VAR_db_user_dw: ${{ secrets.DB_USER_DW }}

      TF_VAR_alert_email: ${{ secrets.LOG_EMAIL }}
      TF_VAR_log_email_pass: ${{ secrets.LOG_EMAIL_PASS }}

    steps:
      - name: Checkout and clone repo
        uses: actions/checkout@v4
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Setup Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCES_KEY }}
      - name: Terraform init
        working-directory: terraform
        run: terraform init
      - name: Destroy Terraform
        working-directory: terraform
        run: terraform destroy -auto-approve

  reset-warehouse:
    runs-on: ubuntu-latest
    name: reset-warehouse

    needs: terraform-destroy
    steps:
      - name: Checkout and clone repo
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.6'

      - name: Make environment
        run: make environment

      - name: Install pg8000
        run: source venv/bin/activate && pip install pg8000==1.31.2

      - name: Run format
        run: make format-check

      - name: Run security checks
        run: make security

      - name: Reset warehouse
        run: source venv/bin/activate && export PYTHONPATH=$(PWD) && python src/reset_warehouse/reset.py   
