name: CI Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    name: run-tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout and clone repo
        uses: actions/checkout@v4
      
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.6'

      - name: Make environment
        run: make environment

      - name: Install requirements
        run: make requirements

      - name: Run format
        run: make format-check

      - name: Run security checks
        run: make security

      - name: Run tests
        run: make run-tests

  deploy-lambda:
    runs-on: ubuntu-latest
    name: deploy-lambda
    needs: run-tests
    environment: dev
    steps:
      - name: Checkout and clone repo
        uses: actions/checkout@v4
      - name: Install terraform
        uses: hashicorp/setup-terraform@v3
      - name: Debug AWS Credentials
        run: |
          echo "AWS Region: $AWS_REGION"
          echo "AWS Access Key: ${AWS_ACCESS_KEY_ID:0:4}********"
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}

      - name: Setup credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region : ${{ secrets.AWS_REGION }}
          aws-access-key-id : ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key : ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Terraform init
        working-directory: terraform
        run: terraform init
      - name : Terraform format
        working-directory : terraform
        run: terraform fmt
      - name: Terraform validate
        working-directory : terraform
        run: terraform validate
      - name: Terraform plan
        working-directory : terraform
        run: terraform plan
      - name: Terraform apply
        working-directory : terraform
        run: terraform apply -auto-approve