name: CI Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    name: run-tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout and clone repo
        uses: actions/checkout@v4
      
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.6'

      - name: Make environment
        run: make environment

      - name: Install requirements
        run: make requirements

      - name: Run format
        run: make format-check

      - name: Run security checks
        run: make security

      - name: Run tests
        run: make run-tests

  deploy-lambda:
    runs-on: ubuntu-latest
    name: deploy-lambda
    env:
      TF_VAR_db_db: ${{ secrets.DB_DB }}
      TF_VAR_db_host: ${{ secrets.DB_HOST }}
      TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
      TF_VAR_db_port: ${{ secrets.DB_PORT }}
      TF_VAR_db_user: ${{ secrets.DB_USER }}
      TF_VAR_alert_email: ${{ secrets.LOG_EMAIL }}
      TF_VAR_log_email_pass: ${{ secrets.LOG_EMAIL_PASS }}
    needs: run-tests
    steps:
      - name: Checkout and clone repo
        uses: actions/checkout@v4
      - name: Install terraform
        uses: hashicorp/setup-terraform@v3
      - name: Setup credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region : ${{ secrets.AWS_REGION }}
          aws-access-key-id : ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key : ${{ secrets.AWS_SECRET_ACCES_KEY }}
      - name: Terraform init
        working-directory: terraform
        run: terraform init
      - name : Terraform format
        working-directory : terraform
        run: terraform fmt
      - name: Terraform validate
        working-directory : terraform
        run: terraform validate
      - name: Terraform plan
        working-directory : terraform
        env:
          TF_VAR_db_user: ${{ secrets.DB_USER }}
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
          TF_VAR_db_host: ${{ secrets.DB_HOST }}
          TF_VAR_db_db: ${{ secrets.DB_DB }}
          TF_VAR_db_port: ${{ secrets.DB_PORT }}
          TF_VAR_log_email": "${{ secrets.LOG_EMAIL }}"
          TF_VAR_log_email_pass": "${{ secrets.LOG_EMAIL_PASS }}"
        run: terraform plan
      - name: Terraform apply
        working-directory : terraform
        run: terraform apply -auto-approve